version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17  # Use the Jenkins image with JDK 17
    container_name: jenkins-container
    ports:
      - "8081:8080"  # Jenkins UI port
      - "50000:50000"  # JNLP agent port
    volumes:
      - jenkins-data:/var/jenkins_home  # Persist Jenkins data
    environment:
      - JENKINS_INSTALL_PLUGINS=jira:latest  # Automatically install JIRA plugin
    restart: always
volumes:
  jenkins-data:

